#!/usr/bin/env python
"""
This script generates a valid cut string from a JSON file,
which specifies a list of runs and luminosity sections.
The output can be fed into other scripts as cut string.
Note, that you can write the output of this script either
to a file with './jsonToCut cut.json > outputFile' or to
a shell variable with 'CUT=$(./jsonToCut cut.json)'.
"""

import argparse
import json

#----------------------
# Setup argument parser
#----------------------

PARSER = argparse.ArgumentParser(description=__doc__)

PARSER.add_argument("fileNameInput", help="Path to the input JSON file")
ARGS = PARSER.parse_args()

#---------------
# Read JSON file
#---------------

with open(ARGS.fileNameInput, 'r') as f:
    JSON = json.loads(f.read())

#---------------
# Get cut string
#---------------

CUT_STRING = ""
IS_FIRST_RUN = True
for run, lumiRanges in JSON.iteritems():
    # Process run
    if not IS_FIRST_RUN:
        CUT_STRING += " || "
    IS_FIRST_RUN = False
    CUT_STRING += "( run==" + str(run)  + " && ( "

    # process lumi
    isFirstRange = True
    for lumiRange in lumiRanges:
        if not isFirstRange:
            CUT_STRING += " || "
        isFirstRange = False
        CUT_STRING += "( lumi>=" + str(lumiRange[0])  + " && lumi<=" + str(lumiRange[1]) + ")"

    CUT_STRING += " ) ) "

#-----------------------
# Print string to stdout
#-----------------------

print(CUT_STRING)
